### ISSUE TITLE
Input data lost after search / filter - v2.0 - Feature request

### ISSUE THREAD

**Issue by lamka02sk** [xaksis/vue-good-table#212] opened 2018-03-21 19:56 UTC
This is probably not a bug, I think it is done on purpose, that when I update cell value inside row prop and then emit event to my root component, data inside table component are not updated. This is why they get lost and are reset to defauls after search or column filter action. Would be nice to have these edited data updated.

**Comment by xaksis** [comment] 2018-03-21 23:06
@lamka02sk can you please create a fiddle to show this behavior? would be easy for me to plan a course of action once I see it.

**Comment by lamka02sk** [comment] 2018-03-22 08:55
@xaksis I created a simple fiddle, but I use always rather .vue single file components, so this demo somehow does not wanna work, but I believe it would be 30 seconds for you to fix...https://jsfiddle.net/t4ugvqcu/27/

**Comment by xaksis** [comment] 2018-03-22 11:21
you were correct in that this is not a bug but by design. the data within the table is a copy of your original data which is why you can filter/sort etc without affecting your original component data. so you should not be modifying the data in the table, but the original data in your component by using `rows[props.row.originalIndex]`

Refer to the checkbox example here, where the checkbox v-model is set on `v-model="rows[props.row.originalIndex].selected"` on line 16
https://jsfiddle.net/aks9800/keLjcssn/

closing.

**Closed by xaksis** 2018-03-22 11:21 UTC
