### ISSUE TITLE
hyphen breaking search

### ISSUE THREAD

**Issue by thelowellgallery** [xaksis/vue-good-table#166] opened 2018-01-26 01:12 UTC
A search of column data is not returning rows in which the searched string comes after a hyphen. Thanks!

**Comment by xaksis** [comment] 2018-01-26 14:16
@thelowellgallery can you please create a jsfiddle so I can see what the problem is?

**Comment by xaksis** [comment] 2018-01-27 00:41
hey @thelowellgallery, hyphen doesn't break the search, the default search matches 'starts-with' as opposed to 'includes' which means if you filter with middle letters, it won't match the row. 

you can add your own filter to the column like so: 
```javascript
filter: function(data, filterString) {
      return string.indexOf(substring) !== -1;
    }
```

jsfiddle: https://jsfiddle.net/aks9800/obfky53g/2/

closing.

**Closed by xaksis** 2018-01-27 00:41 UTC

**Comment by thelowellgallery** [comment] 2018-01-27 00:43
Ah, got it. Thanks! Sorry to bother.
