### ISSUE TITLE
vue good table footer

### ISSUE THREAD

**Issue by fsfj** [xaksis/vue-good-table#164] opened 2018-01-25 05:40 UTC
Hello, i want to add footer in table. Is it possible? how can i do that?

Thank you.

**Comment by xaksis** [comment] 2018-01-26 14:20
This isn't possible as of now. but there's an enhancement request for this. 

Duplicate of #115

**Closed by xaksis** 2018-01-26 14:20 UTC

**Comment by fsfj** [comment] 2018-01-29 01:44
Thank you @xaksis
