### ISSUE TITLE
Selecting all rows from current page

### ISSUE THREAD

**Issue by stuartjnelson** [xaksis/vue-good-table#233] opened 2018-04-09 01:58 UTC
### Issue Type 
- [x] Question

### Specs
What version are you using? `2.0.5`

What browser? `Chrome 64.0.3282.186`

### Question
Hello! I was hoping to be able to select the checkbox in the header row and then return only the rows from the current page. How would you go about getting just the rows from the current paginated page?

### jsfiddle
[checkbox table fork](https://jsfiddle.net/eyduxn5a/3/)

**Comment by xaksis** [comment] 2018-04-10 00:11
Hi @stuartjnelson I have updated the example to select/deselect all rows: https://jsfiddle.net/aks9800/keLjcssn/

Currently there's no good way to select only the items on the current page. Having said that, I do think this is a good feature request, and I'll work on adding that in.

**Comment by stuartjnelson** [comment] 2018-04-10 02:47
Hey @xaksis,

Thanks for that! Let me know if you need help testing that

**Comment by xaksis** [comment] 2018-04-10 12:01
@stuartjnelson what would you think is the expected behavior if I
1. select all on the current page
2. then change page or filter
it would not make sense to still have the selectAll checkbox checked... since none of the items on the next page would be selected. would you just reset your selection to none? 

or does it make more sense for selectAll to really just be select all rows and not just the visible ones?

**Comment by xaksis** [comment] 2018-04-11 00:31
@stuartjnelson with `v2.1.0` you should now be able to do this with a much cleaner interface. checkout the working example with paging: 
https://jsfiddle.net/aks9800/dzka5qz0/

closing this.

**Closed by xaksis** 2018-04-11 00:31 UTC
Labels: enhancement

**Comment by stuartjnelson** [comment] 2018-04-27 04:34
Hi @xaksis,

Sorry, its taken me ages to reply! That's an awesome update thank you! You've added loads of functionality.

Say I wanted all but one cell in the row to fire `@on-row-click`. Is this possible? 

<img width="587" alt="screen shot 2018-04-26 at 21 33 44" src="https://user-images.githubusercontent.com/5795894/39344808-8895adee-4999-11e8-993b-bdf89adc3007.png">
