### ISSUE TITLE
line number of remote mode reset when sorting

### ISSUE THREAD

**Issue by qwerty7415963** [xaksis/vue-good-table#885] opened 2021-09-14 11:14 UTC
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.21.10

What browser?
Chorme

### Expected Behavior
when I click the sort button line number keeps the same as the setCurrentPage (21-40 ,current page: 2)

### Actual Behavior
the line number reset to 1-20 on page 2

### Steps to Reproduce the Problem

1 .click the sort icon
2. fetching data from api
3. here is the result
![image](https://user-images.githubusercontent.com/34638478/133247751-98f2dcc2-2c86-443e-8b9e-e174ed9888c1.png)

**Comment by xaksis** [comment] 2021-09-29 15:31
Hey @qwerty7415963, this is by design and standard for most sortable tables. When you're on a given page and hit sort, it shouldn't just sort that page, but the entire table of data. The user should see the sort beginning from the start, whether ascending or descending. 
closing.

**Closed by xaksis** 2021-09-29 15:31 UTC
