### ISSUE TITLE
Paging Server Side with VGT

### ISSUE THREAD

**Issue by ELIDJEAKA** [xaksis/vue-good-table#471] opened 2018-12-03 12:24 UTC
### Paging server side with VGT
Hi, I work on a project where the pagination is server side.
I would like to use VGT server side for pagination but I can not do it ...
`data: {current_page: 1,…}
current_page: 1
data: [{id: 5, entite_id: 1, name: "Test Distributeur", email: "akaelidje2@consultech.ci",…},…]
first_page_url: "http://127.0.0.1:8000/api/mesutilisateurs?page=1"
from: 1
last_page: 1
last_page_url: "http://127.0.0.1:8000/api/mesutilisateurs?page=1"
next_page_url: "http://127.0.0.1:8000/api/mesutilisateurs?page=2"
path: "http://127.0.0.1:8000/api/mesutilisateurs"
per_page: 10
prev_page_url: null
to: 7
total: 7
message: "Utilisateurs trouvés."
success: true`
so I want to have a sample code
I would like to call the following page by the url: next_page_url and also the filter per page
Thanks...

**Comment by ow-en** [comment] 2019-01-25 16:42
Please follow the issue template in the future, it makes the issue easier for everyone involved to address.

Regarding your question: It's difficult  for me to determine where the issue is based on the format of your issue. What I can say is this: pagination, sort, and filter are all controlled by your own server-side logic when in remote mode.

In remote mode, the plugin emits events when page, sort, filter, etc. are changed. These events are caught by their corresponding methods, and channeled into the loadItems method. If you are having issues with the lifecycle of events, I would debug the client using vue-devtools to ensure that the events are firing as intended. 

From there, all of the pagination, filter, sort functionality is up to you to create in your own server logic. For pagination, I recommend researching a skip/take operation. If there is in fact an issue with the client-side event emission, or a plugin-related bug that I'm not aware of, feel free to repost this issue with the correct template. Closing for now.

**Closed by ow-en** 2019-01-25 16:42 UTC
