### ISSUE TITLE
Fields with decimal points in them are not showing up in the table

### ISSUE THREAD

**Issue by Alan-Solitar** [xaksis/vue-good-table#521] opened 2019-03-13 05:44 UTC
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
Latest
What browser?
Firefox

### Expected Behavior
What did you expect to happen?
Each row is formatted like this:
```
{
'22.5':<number>,
'25':<number>,
'27.5':<number,
etc,,,
}
```
The columns are using field names that correspond to the object keys.
I expect all values to show up in the table under the correct columns.
### Actual Behavior
What actually happened?
Any properties in my rows that have decimal points in them are not showing up.
For example, anything with a whole number as the key, like '25,'27',etc.... is showing up fine.
However, data with decimal points in them like '25.5','27.5', etc... are not showing up in the table.

**Comment by ow-en** [comment] 2019-03-13 06:58
@Alan-Solitar 

Can you give me a snippet of your columns object, or provide a fiddle reproducing the issue?

Second, have you set the 'Type' prop as 'Decimal' for the column(s) with floating point values? See the type prop in the documentation (here)[https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#type].

The columns default their type to String, which I've noticed isn't an issue with whole numbers (I believe due to implicit conversion), but I've noticed that floating point integers can cause problems in columns that don't have the 'Decimal' type prop set.

If that doesn't correct the issue, it might be worth considering the use of a format function (docs (here)[https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#formatfn].

The format function could simply return your value, which (iirc) would do an end-run around the column's default String type, returning your floating point instead. Don't take this as gospel, though - it's late and I would need to test this to double-check - but I'm fairly sure I've done something similar in the past.

If neither of those solve the issue, reply back with a fiddle and myself or @xaksis would be happy to take a look. Thanks for using vgt.

**Comment by ow-en** [comment] 2019-03-13 07:42
@Alan-Solitar 

I just want to make sure I'm clear on the issue: the concern here is that row values whose column fields (object keys) are floating point numbers aren't showing up?

If that is the case, I was able to reproduce this in a fiddle, though I'm not sure this is a bug.

If you look at the fieldFn in the [docs](https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#field), the column is being saved as an object. If your column field were '22.5', this wouldn't work:
`return rowObj.22.5`

Using floating point integers as object keys/columns in data isn't a practice I've seen recommended nor one that I've personally encountered. 

In JavaScript, using floating point numbers as object keys is _okay_ , in theory. See the below from StackOverflow regarding using floating point integers as object keys:

> The floating-point numbers used by JavaScript (and most other languages) aren't perfectly precise; so if you did this:
> 
> obj[0.3] = 10;
> and then
> 
> var key = 0.1;
> key += 0.2;
> console.log(obj[key]); // undefined
> That's undefined because 0.1 + 0.2 comes out to 0.30000000000000004, rather than 0.3, and your object doesn't have a property named 0.30000000000000004.
> 

Whether the issue is being caused by the above behavior, and whether or not support for this is intended within vgt are things I'm personally unsure of - @xaksis , would you be able to shed some light on this, if anything comes to mind?

**Comment by Alan-Solitar** [comment] 2019-03-13 16:07
@ow-en Yeah, your interpretation of the problem is correct.  The only reason for using keys like this is because is because that is already the way the javascript object is already formatted.  If it's not necessarily a  bug, then I suppose I can find a workaround of some sort.

**Comment by xaksis** [comment] 2019-03-15 00:00
hey @Alan-Solitar yeah, @ow-en is right about this not being a bug. The reason decimals don't work is because the dot notation is actually used to look up nested objects. in other words if `user.name` would actually look for: 
```javascript
{
  user: {
    name: 'Alan',
  },
}
```

Table doesn't have any way to know whether you're looking for a nested field or a decimal field.

closing.

**Closed by xaksis** 2019-03-15 00:00 UTC

**Comment by carmolim** [comment] 2021-10-27 21:55
I'm with a similar situation, the data from the API I'm using is return some fields with a dot  `ip.count` or `bytes_sent.avg` is possible to disable this behavior?
