### ISSUE TITLE
Error while using Typescript

### ISSUE THREAD

**Issue by rafaelgov95** [xaksis/vue-good-table#310] opened 2018-06-19 12:08 UTC
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
2.7.2
What browser?
Google Chrome

### Steps to Reproduce the Problem
Please detail your steps here

1.
How to use typescript VueTS

**Comment by xaksis** [comment] 2018-06-20 12:52
duplicate of #280. will be fixed shortly.

**Closed by xaksis** 2018-06-20 12:52 UTC

**Comment by xaksis** [comment] 2018-06-20 13:04
@rafaelgov95 component export should now be fixed with v2.8.1.

import { VueGoodTable from }  from  'vue-good-table';

export default {
  components: {
    VueGoodTable,
  },
  (...)
};
Install instruction for your ref:
https://xaksis.github.io/vue-good-table/guide/#installation

**Comment by rafaelgov95** [comment] 2018-06-20 13:54
Not Run!!!!! SOS!
```
import { VueGoodTable } from 'vue-good-table';

// add to component
components: {
  VueGoodTable,
}
```
Error 

Could not find a declaration file for module 'vue-good-table'. '/home/rafael/Documentos/Materias/TES/Trabalho-III/compras-front/node_modules/vue-good-table/dist/vue-good-table.cjs.j
s' implicitly has an 'any' type.
  Try `npm install @types/vue-good-table` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-good-table';

**Comment by xaksis** [comment] 2018-06-20 14:10
you are trying to import an es module directly as a typescript component. refer to #280 to see how to properly import es component.
