### ISSUE TITLE
Selecting all visible rows

### ISSUE THREAD

**Issue by HorstBrack** [xaksis/vue-good-table#237] opened 2018-04-11 07:29 UTC
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.1.0
What browser?
Chromium
### Expected Behavior
What did you expect to happen?
Checkbox "select all" selecting all on the current page, then after changing to the next page,
"select all" selecting all there in addition
### Actual Behavior
What actually happened?
"Select all" on consecutive page voids previous selection

### Steps to Reproduce the Problem
Please detail your steps here

This is a followup to https://github.com/xaksis/vue-good-table/issues/233
I tried out the fiddle and it has a problem:
I click "select all" on page one, then go to page 2, click "select all" there.
Both only select the visible checkboxes. OK.
But when I now go back to page 1 the selections are gone.

This behaviour repeats with single selections as well.
In effect it is now impossible to make and memorize selections across pages.

**Comment by xaksis** [comment] 2018-04-11 10:58
@HorstBrack this is by design. selectAll only selects the visible rows. If you move to the next page, filter, or sort, the selectAll checkbox is unchecked and the selection is reset. selectAll needs to be reset because otherwise, you'd have the selectAll checkbox checked while nothing would be selected on the next page. 

Similarly, you might select all to select all visible rows and then try to filter or sort, at which point the selectall visible rows is not valid anymore.

But I see your point, I'll think of a more intuitive behavior on paging etc. What do you think should happen to your selection when you move to the next page, filter, sort etc?

Also, individual selections are visually maintained through paging, sorting etc. if you're not acting on them right away, you'd have to keep track of what rows are selected/unselected via on-row-click handler.

**Comment by HorstBrack** [comment] 2018-04-11 15:01
Ok, maybe it is easier to explain what I have here:
There is a list with 1000 domains.
I want to be able to browse through all domains, mark those I wish to delete and when I am done press "delete" to kill them all.
Right now this is not possible. 
What I believe would be more intuitive is that the state of the checkboxes is maintained throughout page changes.
Is this possible?

**Comment by xaksis** [comment] 2018-04-11 22:15
alright! I think this should solve all your issues, as a bonus, I also created a new slot for you to put your action button in. 
https://jsfiddle.net/aks9800/dzka5qz0/

closing.

**Closed by xaksis** 2018-04-11 22:15 UTC

**Comment by HorstBrack** [comment] 2018-04-12 08:07
Cool, thanks :)
