### ISSUE TITLE
Detail row feature

### ISSUE THREAD

**Issue by PrimozRome** [xaksis/vue-good-table#541] opened 2019-04-25 07:20 UTC
- [x] Enhancement Request

### Expected Behavior
Have option to enable detail row. This means that each row would have a [+] button in the first column (or last) which would toggle detail row on/off. Detail row should be a component that receives few props like row object, etc...

Something like this:

<img width="2122" alt="Screenshot 2019-04-25 at 09 18 58" src="https://user-images.githubusercontent.com/1180467/56716763-6c58c880-673b-11e9-953e-5e65fa9af9fc.png">

**Comment by xaksis** [comment] 2019-04-26 07:11
duplicate of #425 
closing.

**Closed by xaksis** 2019-04-26 07:11 UTC

**Comment by PrimozRome** [comment] 2019-04-26 07:25
@xaksis thanks, appreciate it!
