### ISSUE TITLE
Checkbox all do not uncheck all when data loaded via ajax

### ISSUE THREAD

**Issue by sergeevpasha** [xaksis/vue-good-table#256] opened 2018-04-20 04:08 UTC
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs

What version are you using?
2.4.1

What browser?
Chrome/Firefox/IE/Opera/Safari

### Expected Behavior
Checkbox All should actually check and uncheck all

### Actual Behavior
In fact it only checks all, but never uncheck (However in console log i can see that everything is ok, but visually - no)

**Comment by sergeevpasha** [comment] 2018-04-20 04:09
I did actually check out some older versions, but that didnt help me at all

**Comment by sergeevpasha** [comment] 2018-04-20 04:30
i locolized the problem:
```
<script>
export default {
    name: 'products',
    beforeCreate: function() {
        this.$http.get('/getData')
        .then(function(response) {
            console.log(response);
            this.rows = response.data;
        });
    },
    data() {
        return {
            columns: [{
                label: 'Наименование',
                field: 'name',
                filterOptions: {
                    enabled: true,
                },
            },{
                label: 'Цена',
                field: 'price',
                type: 'number',
            }, {
                label: 'Created On',
                field: 'createdAt',
                type: 'date',
                dateInputFormat: 'YYYY-MM-DD',
                dateOutputFormat: 'DD-MM-YYYY',
            }, {
                label: 'Percent',
                field: 'score',
                type: 'percentage',
            },
        ],
            rows: []
        };
    },
    methods: {
  		selectAll(selected, selectedRows) {
      	// do what you want here
      	console.log(selected, selectedRows);
      },
      toggleSelectRow(params) {
      	// row that was clicked
      	console.log(params.row);
        // index of page
        console.log(params.pageIndex);
        // whether the row was selected or unselected
        console.log(params.selected);
      }
    },
    mounted() {
  	},
};
</script>
```
if i will add data manualy into rows: [] everyting really works. But when i try to add data via http request - its not.
Help me, is that really a bug or i am doing smth wrong

**Comment by xaksis** [comment] 2018-04-20 11:58
@sergeevpasha I was able to reproduce this on my end. will debug further to see what is going wrong.

**Comment by jprivillaso** [comment] 2018-04-20 13:13
I was facing the same issue.
In my case the error was that in the older version, the date columns had these two properties: 

- inputFormat
- inputFormat

In the new version, those properties were changed to

- dateInputFormat
- dateOutputFormat

After changing that, the clear/unclear worked.

**Comment by jprivillaso** [comment] 2018-04-20 13:51
I am facing the same issue. 
I don't know if it is related but errors start appearing when you use vue-router and somehow it keeps old references to the older table.

On my end, I have a menu with different menu items that correspond to different pages. 
I have a dynamic route that is used on all the pages. E.g /app/:table_name

On that route, I render a table that displays the data from the `table_name`. This data comes from the server. If I load a route for the first time, it works, however when I change from one route to another one that has the same URL patter, it stops working. 

I'm not sure how the table is storing the references of the selected rows, because I'm logging the selected rows inside the method ` @on-select-all="selectAll"` and selectRows is empty.

**Comment by xaksis** [comment] 2018-04-20 14:02
@sergeevpasha your issue should be fixed with version 2.4.3. 
here's a working checkbox example that loads data from a remote server: https://jsfiddle.net/aks9800/mc2sfkjb/

@jprivillaso your issue seems to be related to vue-routing and not vue-good-table. vue caches your route components and changing the route parameter does not guarantee a refresh of all components. 

You'll see examples of how to correct this if you look this up online. for example - https://laracasts.com/discuss/channels/vue/vue-2-reload-component-when-same-route-is-requested

@on-select-all sends one parameter object. if you `console.log(params);` it you'll see selectedRows as one of the properties within params.

closing.

**Closed by xaksis** 2018-04-20 14:02 UTC
Labels: bug

**Comment by sergeevpasha** [comment] 2018-04-20 14:03
@xaksis 
thx, works great now

**Comment by jprivillaso** [comment] 2018-04-20 17:58
@xaksis Thanks!! 
Indeed I though it was an issue with vue-router. However, I still can make it work 😞
