### ISSUE TITLE
Issue sorting columns

### ISSUE THREAD

**Issue by jprivillaso** [xaksis/vue-good-table#213] opened 2018-03-22 13:39 UTC
When data type of the rows is different than String, it throws an error because the method `compare` is trying to execute this line of code: 

```
function cook(d) {
      if (typeof d === 'undefined' || d === null) return '';
      return d.toLowerCase();
}
```

`toLowerCase` function only exist for strings.

**Comment by xaksis** [comment] 2018-03-22 13:49
hey @jprivillaso by default, your data type is treated as string. Did you specify a type for your column?

**Comment by jprivillaso** [comment] 2018-03-22 13:53
Hi! Thanks for you super fast answer.
Actually, I make a server call that retrieves data in its original format and then I return it. I have it wrapped inside the computed method `columns`.
Then answer to your question is no, i'm not specifying the type.

Thanks

**Comment by xaksis** [comment] 2018-03-22 13:55
ah yeah, without `type` sort behavior will be unpredictable for dates/numbers etc... so this is by design. going to close this.

**Closed by xaksis** 2018-03-22 13:55 UTC

**Comment by jprivillaso** [comment] 2018-03-22 14:21
Awesome. 
Thanks :) Working now 🥇 👍

**Comment by atravotum** [comment] 2019-01-31 16:33
I'm having the same issue but specifying a "type":"number" on the column configurations does NOT fix the issue. I still run into the d.toLowerCase. This can be avoided by simply enforcing the value as a string, or adding some logic to check if toLowerCase is a valid function before calling it.

**Comment by gunkiddedy** [comment] 2020-11-30 16:27
thankyou, dude... :-)
