### ISSUE TITLE
styleClass doesn't seem to work

### ISSUE THREAD

**Issue by ken-sands** [xaksis/vue-good-table#9] opened 2017-06-06 13:52 UTC
if I change the default in the vue it works but if I try to set it in the html it has no effect.

**Comment by xaksis** [comment] 2017-06-06 15:28
hey @ken-sands can you provide some example code so I can reproduce it on my end? thanks.

**Comment by xaksis** [comment] 2017-06-24 18:05
closing this. Please re-open if you are still seeing the issue with an example.

**Closed by xaksis** 2017-06-24 18:05 UTC

**Comment by sushant-j** [comment] 2017-08-21 07:06
I have an issue with something similar. 
The table adds .responsive as a container for the actual table.
Is there any way to remove/modify this class?

**Comment by xaksis** [comment] 2017-08-21 12:00
hey @sushant-j can you explain your issue a little? are you having a name-clash with 'responsive'? or is it resulting in some unwanted behavior? a screenshot might also help.

**Comment by sushant-j** [comment] 2017-08-21 12:11
No, I am not having any name clash as such. The only thing is, I don't want that class as a container, as it adds overflow-x: scroll along with a 100% width. 

Right now, I am overriding it, but I have to use the generated hash from the plugin to style it. 

```
.responsive[data-v-0cff0041] {
  overflow: hidden !important;
}
```

I would like to know if there's any way I could control this class or related styles.

**Comment by xaksis** [comment] 2017-08-21 12:31
@sushant-j ok... so if i understand it right, when the screen width is smaller than your table width, you want to hide your content rather than scroll horizontally? 
just to make sure we're on the same page, that class is only relevant if your table is wider than your screen width. The default behavior then is, overflowed content will be hidden and your users will never be able to view the hidden content... unless they make the window wider.

what I can do, is make that class optional so you can revert to default behavior... but just wanted to make sure there's a real usecase for this, because addition of responsive container was the result of many asking to avoid the default behavior.

**Comment by sushant-j** [comment] 2017-08-21 12:57
Yes, when the table is wider than the viewport, I want it hidden. I also apply hide classes to certain columns in that scenario (using thClass prop), which allows me to show a smaller subset of columns on smaller viewport widths (think mobiles, tabs, etc.)

It would be great if you could make that class optional for above reason.

**Comment by xaksis** [comment] 2017-08-21 13:44
ok cool, i'll make it optional in the next patch release. will create a new issue for this
