### ISSUE TITLE
Fixed header and horizontal scrolling don't work 

### ISSUE THREAD

**Issue by ProcopVladimirAlexandru** [xaksis/vue-good-table#696] opened 2020-04-06 15:15 UTC
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.19.1 (latest)
What browser?
Mozilla Firefox and Chrome
### Expected Behavior
What did you expect to happen?
When using fixed header and a wider table that requires horizontal scrolling I expected that the column names in the header will match the actual columns being horizontally scrolled scrolled through.
### Actual Behavior
What actually happened?
The header column names do not allign properly and have wrong width when scrolling horizontally.
![image](https://user-images.githubusercontent.com/26043668/78574311-7d0e2b80-7832-11ea-8be5-1fbead28483f.png)
### Steps to Reproduce the Problem
Please detail your steps here

1. Use vue good table with fixed header
2. Populate the table with a dataset with many wide columns
3. There is a scroll bar for header and one for actual data instead of a single data scroll which simultaneously scrolls through the header.

**Comment by xaksis** [comment] 2020-05-09 18:57
duplicate of #697

**Closed by xaksis** 2020-05-09 18:57 UTC
