### ISSUE TITLE
Question: Is there any way by which I can enable/disable checkbox for specific rows based on specific condition? 

### ISSUE THREAD

**Issue by coolgeekpc** [xaksis/vue-good-table#718] opened 2020-06-02 18:06 UTC
### Issue Type
- [x] Question

### Specs
What version are you using?
"^2.18.0"
What browser?
Chrome

### Expected Behavior
What did you expect to happen?
My question is related to Checkbox Table. Is there any way by which I can enable/disable checkbox for specific rows based on specific condition? Something like shown in below image where Klaas and Christine are disabled and which user check select all those disabled checkboxes should not be selected.

![image](https://user-images.githubusercontent.com/13234456/83553739-4e0df080-a529-11ea-8b51-f06269a4483a.png)

**Comment by xaksis** [comment] 2020-06-23 00:16
yeah, you can use the internal row property, vgtSelected. Refer to this issue:
https://github.com/xaksis/vue-good-table/issues/592

closing.

**Closed by xaksis** 2020-06-23 00:16 UTC

**Comment by Quang-Dong** [comment] 2021-04-12 10:13
> 
> 
> yeah, you can use the internal row property, vgtSelected. Refer to this issue:
> #592
> 
> closing.

I tried, but the problem is *DISABLED the checkbox*, not update the data. Hope you reply soon, thank you!
