### ISSUE TITLE
drop-down all option in server side mode not working

### ISSUE THREAD

**Issue by Alirezanet** [xaksis/vue-good-table#336] opened 2018-07-17 04:04 UTC
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.9.0
What browser?
chrome
### Expected Behavior
show all records after selecting All option in paging bar

all option perPage value should be equal to totalRecords

### Actual Behavior

after selecting all option, perPage value is -1

**Comment by xaksis** [comment] 2018-07-17 11:02
@Alirezanet this is by design. In order to specify 'all' records to the server, you need a non-positive integer value. You can either make a change at the server indicating that -1 == all records... or add a condition in 'on-per-page-change' to catch -1 and change it to whatever value you want to send to the backend. 

closing.

**Closed by xaksis** 2018-07-17 11:02 UTC
