### ISSUE TITLE
(Help Required) Header stacked vertically by default

### ISSUE THREAD

**Issue by IAmShafqatAli** [xaksis/vue-good-table#820] opened 2021-02-24 15:25 UTC
Hi,
Thank you for the great plugin, I really appreciate the effort.
I am having a problem, don't know why it is happening like that maybe a little help can save me alot of time.

By simple data loaded my header is stacked horizontally. Body of the table is shown as expected. 

Is this something wrong with my configuration ? 

![image](https://user-images.githubusercontent.com/40568550/109023126-cc648100-76bc-11eb-97bc-248a9e2a5565.png)

**Comment by xaksis** [comment] 2021-02-27 19:00
It'll be tough to help you without seeing the code, @IAmShafqatAli looks like there's some malformed tags. Can you create a jsfiddle or codepen to demonstrate?
I'll close this now, lets re-open once there's a reproducible example.

**Closed by xaksis** 2021-02-27 19:00 UTC

**Comment by IAmShafqatAli** [comment] 2021-06-28 16:46
@xaksis I am so sorry, I totally forgot to mention that it was the problem from my side, I actually was using sortable js and for that I had one custom class with the name **sortable** which was actually messing up the whole table header class. I fixed it and everything is fine. Sorry for late reply but thank you so much for your reply, I really appriciate it. 
Cheers :)
