### ISSUE TITLE
If fixed header is set, it's duplicated and columns don't respect the specified width

### ISSUE THREAD

**Issue by therobotacademy** [xaksis/vue-good-table#740] opened 2020-08-04 18:38 UTC
### Issue Type

- [x] Bug

### Specs
What version are you using?
2.20.0

What browser?
Chrome

### Expected Behavior
What did you expect to happen?
 - Only one row header should appear
 - And it should be synced with the table content when scrolling to the right
 - The header should respect the width set for each column

### Actual Behavior
What actually happened?
 - Duplicated header rows appear
 - The columns of the fixed header doesn't have the specified width for columns
 - Fixed header doesn't scroll laterally with the table content (move to the right of the rows)

### Steps to Reproduce the Problem
Please detail your steps here

1. Set `:fixed-header="true"`
1. Specify `max-height="150px"`, i.e. a value in which the number of rows per page (10) doesn't fit in that height
1. Add more rows (+8) to make the effect appear (see Fiddle)

### jsfiddle
This fiddle reproduces the bug:
https://jsfiddle.net/brjapon/sgnko39w/12/

**Comment by xaksis** [comment] 2020-08-05 02:18
duplicate of https://github.com/xaksis/vue-good-table/issues/697

**Closed by xaksis** 2020-08-05 02:18 UTC

**Comment by rosenfeldalon** [comment] 2021-07-27 15:08
have the same issue and the resolved ticket does not contain the solution.
on browser refresh I get a duplicated header, navigating in and out of the page via routes the fixed header is fine
