### ISSUE TITLE
Column header misalignment

### ISSUE THREAD

**Issue by sigjak** [xaksis/vue-good-table#501] opened 2019-02-18 20:20 UTC
When max-height is enabled, headers and columns are misaligned. See attached fig. Is this a known issue? The translation to the left could be due to the scrollbar width?

regards

Sig

![misaligned](https://user-images.githubusercontent.com/27348716/52974687-5a188200-33ba-11e9-967a-8088c9a507be.PNG)

**Comment by ow-en** [comment] 2019-02-18 23:00
@sigjak can you provide a fiddle reproducing the error? I'd be happy to look into this further.

Thanks,

**Comment by sigjak** [comment] 2019-02-19 12:37
Thanks for the answer. 
The misalignment occurred in an SPA where good-tables is one of several components. I made a simpler version with no other components and that version shows no misalignment on MAC  or Windows
(https://github.com/sigjak/good-table.git) so something is interfering with the table and I must deal with that.
However, the checkbox bug mentioned in #496 is still present. Will there be a fix for that soon?

regards and thanks for the help

Sig

**Comment by sigjak** [comment] 2019-02-20 12:07
I believe I have found the cause for misalignment reported a couple of days ago. This shows up when **fixed-header is true** in Chrome ( 72.0.3626.109, 64 bit and Firefox (65.0.1 , 64 bit) Windows 10 but not on Mac Chrome, Firefox and Safari, 

regards 
and thanks for fixing the checkbox bug!

**Comment by ow-en** [comment] 2019-02-22 23:07
@sigjak I'm looking into this. Removing the max-height prop corrects the issue (though I haven't yet determined why/where the interference is coming from).

I'll keep you posted as I debug this.

**Comment by xaksis** [comment] 2019-03-12 15:55
duplicate of #373 

closing this. Any update will be posted on 373

**Closed by xaksis** 2019-03-12 15:55 UTC
