### ISSUE TITLE
How to expand width of the specific column?

### ISSUE THREAD

**Issue by deanilvincent** [xaksis/vue-good-table#221] opened 2018-04-02 15:13 UTC
Good day @xaksis 

Is there a way to expand the specific column in the table? 

Suppose I have a column of description and one of the description cell is composed of 100 characters. The problem is, the 100 characters is just fitting horizontal in that cell.

I hope there's a way like I can set a width specifically for one column in the table.

I'm using version:  "1.20.3"

**Comment by xaksis** [comment] 2018-04-02 15:20
use the `width` property in column definition. 
https://github.com/xaksis/vue-good-table#width-number

this works the same way in 1.x 

closing.

**Closed by xaksis** 2018-04-02 15:20 UTC

**Comment by deanilvincent** [comment] 2018-04-02 15:28
Yes, I already tried using width before. But when I tried to create a sample description word by word, I got this kind of result.

![vuetabletest](https://user-images.githubusercontent.com/10904957/38202182-71fdb182-36cd-11e8-9c72-3dd67eedee45.PNG)

Instead of horizontal expansion.

**Comment by xaksis** [comment] 2018-04-02 16:36
@deanilvincent can you create a jsfiddle reproducing this? I would like to take a look. I suspect the issue is more with how html tables work rather than vue-good-table itself.

**Comment by deanilvincent** [comment] 2018-04-03 03:06
I have this similar codes:

[https://jsfiddle.net/kpzexmL4/11/](url)
