### ISSUE TITLE
Column filters resetting each other if filling out multiple at once

### ISSUE THREAD

**Issue by K1ngMX** [xaksis/vue-good-table#808] opened 2021-01-27 12:23 UTC
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.21.1
What browser?
Chrome / Firefox / Edge
### Expected Behavior
I have a table which has columnFilters set for every column:
![image](https://user-images.githubusercontent.com/5102870/105987664-e0f23100-609e-11eb-99b7-32af15a60c23.png)
All the columns are currently set to trigger on "enter".
When i fill out all the values:
![image](https://user-images.githubusercontent.com/5102870/105987737-fcf5d280-609e-11eb-89cc-4b7f1c1bf4f4.png)
and then press "enter" on the last one:
![image](https://user-images.githubusercontent.com/5102870/105987829-1d259180-609f-11eb-9225-48b7eb206645.png)
it does reset the other filter values:
![image](https://user-images.githubusercontent.com/5102870/105987866-2adb1700-609f-11eb-99c1-4d93b5398f87.png)
It seems to me that only the "currently triggering column" is applied to the internal state.

With my limited knowledge it seems like the problem is somewhere here: https://github.com/xaksis/vue-good-table/blob/68530161bd4ee561b12ef771e2bebb9ad17551f4/src/components/VgtFilterRow.vue#L172
It seems like it does apply "the current column" and then emits an event with all current options (so, not the other two changed values), but i could be totally off here.
Any idea what one could do?

### Actual Behavior
What actually happened?

### Steps to Reproduce the Problem
For some reason in the jsfiddle it doesnt show the columnFilters, so i made a small example here (its basically the fiddle with just enabled columnFilters). I can reliably reproduce the behaviour when i select the first filter, type something, press TAB, type something, press TAB, type something (need to do it very quickly to appear)

`<div class="container">
        <div id="app">
            <vue-good-table
                :columns="columns"
                :rows="rows"
            >
            </vue-good-table>
        </div>

        <script type="text/javascript">
            new Vue({
                el: '#app',
                data() {
                    return {
                        columns: [
                            {
                                label: 'Name',
                                field: 'name',
                                sortable: false,
                                filterOptions: {
                                    enabled: true
                                },

                            },
                            {
                                label: 'Age',
                                field: 'age',
                                type: 'number',
                                sortable: false,
                                filterOptions: {
                                    enabled: true
                                },
                            },
                            {
                                label: 'Percent',
                                field: 'score',
                                type: 'percentage',
                                sortable: false,
                                filterOptions: {
                                    enabled: true
                                },
                            },
                        ],
                        rows: [
                            { id:1, name:"John", age: 20,score: 0.03343 },
                            { id:2, name:"Jane", age: 24,  score: 0.03343 },
                            { id:3, name:"Susan", age: 16, score: 0.03343 },
                            { id:4, name:"Chris", age: 55,  score: 0.03343 },
                            { id:5, name:"Dan", age: 40, score: 0.03343 },
                            { id:6, name:"John", age: 20, score: 0.03343 },
                            { id:7, name:"Jane", age: 24  },
                            { id:8, name:"Susan", age: 16,  score: 0.03343 },
                        ],
                    };
                },
            });
        </script>
    </div>`

**Comment by xaksis** [comment] 2021-03-02 01:34
Hey @K1ngMX this behavior is working as designed. In your example, the trigger on each column is explicitly specified to be 'enter' meaning the column filter will only trigger if you hit enter on that column.
What you're doing instead, is inputting value on filter A then moving on without hitting enter (so not triggering the filter) then inputting value on column B, not hitting enter (so not registering the filter) then in column C you actually hit enter. So the only filter that is actually registered is column C because that's the only one that actually received the explicitly mentioned trigger. The other columns never registered the filter because the explicit trigger - 'enter' was never committed.

closing.

**Closed by xaksis** 2021-03-02 01:34 UTC
