### ISSUE TITLE
onSortChange argument is array, not object

### ISSUE THREAD

**Issue by projct1** [xaksis/vue-good-table#487] opened 2019-01-10 18:50 UTC
### Issue Type
Bug

### Version
2.16

### Expected Behavior
```js
/**
@link https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#provide-handlers-for-user-events
*/
onSortChange(params) { //as in docs 
    this.serverParams.sort = {
        type: params.sortType,
        field: this.columns[params.columnIndex].field
    };
    this.loadItems();
}
```

### Actual Behavior
```js
onSortChange(params) {
    this.serverParams.sort = {
        type: params[0].type,
        field: params[0].field
    };
    this.loadItems();
}
```

**Comment by ow-en** [comment] 2019-01-10 23:44
I'm not exactly sure what the issue is here. This is the example serverParms object from the docs:

```js
serverParams: {
  // a map of column filters example: {name: 'john', age: '20'}
  columnFilters: {
  },
  sort: {
    field: '', // example: 'name'
    type: '' // 'asc' or 'desc'
  },

  page: 1, // what page I want to show
  perPage: 10 // how many items I'm showing per page
}
```
If you leave the sort object as shown in the docs, it will return the field name of the column being sorted, and the direction of the sort.

**Comment by projct1** [comment] 2019-01-11 08:07
@ow-en Params argument in `onSortChange` does not match `params` in docs.
Look *Actual Behavior* and *Expected Behavior* above please.

**Comment by ow-en** [comment] 2019-01-16 06:35
@projct1 I apologize, I definitely misread your post. What I think I was getting at was that I believe this functionality is intended.

I don't have it in front of me right now, but I believe if you console.log the params argument, it's just returning the "rows" property. Params[index] would correspond to rows[indexOfColumnInQuestion]. 

Is the array format causing a particular issue with your remote mode workflow? If you could describe it, I might be able to offer a little bit more insight. I've spent a lot of time figuring out how to get remote mode to work properly, so if I can help with any issues - I'd definitely like to.

Best of luck,

**Comment by xaksis** [comment] 2019-01-17 15:02
@ow-en thank you for trying to help!
@projct1 the documentation is a bit outdated here. Vuegoodtable now supports sorting by multiple columns and therefore param objects come back as arrays. I will update the documentation to reflect the change.

**Comment by xaksis** [comment] 2019-03-09 11:31
documentation has now been updated to reflect correctly. closing.

**Closed by xaksis** 2019-03-09 11:31 UTC
Labels: documentation change
