### ISSUE TITLE
on-sort-change page position inconsistent in remote mode

### ISSUE THREAD

**Issue by andriasmelianus** [xaksis/vue-good-table#531] opened 2019-03-27 01:40 UTC
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.16.3

What browser?
Chromium 73

### Expected Behavior
What did you expect to happen?
When user on page 2 (or whatever page except page 1) and sort the records, VGT remain on the page 2.

### Actual Behavior
What actually happened?
VGT reset the pagination showing data from 1 - 10 (for example) of 50. But the the value of `page` in `serverParams` still `2`.
It's okay because we can set the `page` value to `1` when `on-sort-change` fired. But it will great if the pagination preserve the position based on `page` value.

### Steps to Reproduce the Problem
Please detail your steps here

1. Load data from server
2. Click `Next` button to go to the next page
3. Click a column to sort the records

**Comment by xaksis** [comment] 2019-04-26 07:24
reverting back to page 1 on sort change is by design. Consider the following example. You are on page 3 and are looking at rows X, Y, Z. Now you click sort - if you remain on page 3, the rows that you currently see are maybe G, H, I. You sorted the table to see some kind of order in your data but being on page 3 has no value right now. We don't really know where X, Y, Z have gone so to avoid confusion it's better to start from page 1 in the correct sort that user requested. 

Closing.

**Closed by xaksis** 2019-04-26 07:24 UTC
